apiVersion: v1
kind: Service 
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: myapp
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      targetPort: 8080
      - name: https
        port: 8080 
        targetPort: 443